import raw from './population.json'

/**
 * Typed access for the 2025 population estimates (التقديرات السكانية 2025).
 *
 * Generated by scripts/build_population.py from the MOH workbook: one record
 * per health-institution catchment, with Omani / expatriate × male / female
 * counts for 17 five-year age bands (0-4 … 80+). Values are modelled estimates
 * (fractional); round only at display time so totals reconcile to the source.
 */

export type Nationality = 'all' | 'omani' | 'expat'

interface RawInstitution {
  en: string
  ar: string
  wilayat: string
  inSummary: boolean
  omM: number[]
  omF: number[]
  exM: number[]
  exF: number[]
}

interface RawPopulation {
  meta: {
    title: string
    titleAr: string
    source: string
    reference: string
    ageBands: string[]
    summarySheet: { institutions: number; omani: number; expatriate: number }
  }
  wilayats: { en: string; ar: string }[]
  institutions: RawInstitution[]
}

const db = raw as RawPopulation

export const popMeta = db.meta
export const AGE_BANDS = db.meta.ageBands
export const WILAYATS = db.wilayats
export const INSTITUTIONS = db.institutions

/** Per-band male / female counts for one catchment or an aggregate of several. */
export interface Profile {
  male: number[]
  female: number[]
}

const zeros = (): number[] => AGE_BANDS.map(() => 0)
const add = (a: number[], b: number[]): number[] => a.map((v, i) => v + (b[i] ?? 0))
const sum = (a: number[]): number => a.reduce((acc, v) => acc + v, 0)
/** Sum of bands [from, to] inclusive. */
const range = (a: number[], from: number, to: number): number => sum(a.slice(from, to + 1))

/** Age-band profile of one institution for the chosen nationality. */
export const profileOf = (inst: RawInstitution, nat: Nationality): Profile => ({
  male:
    nat === 'omani' ? inst.omM : nat === 'expat' ? inst.exM : add(inst.omM, inst.exM),
  female:
    nat === 'omani' ? inst.omF : nat === 'expat' ? inst.exF : add(inst.omF, inst.exF),
})

/** Combine several institutions into one profile. */
export const aggregate = (list: RawInstitution[], nat: Nationality): Profile =>
  list.reduce<Profile>(
    (acc, inst) => {
      const p = profileOf(inst, nat)
      return { male: add(acc.male, p.male), female: add(acc.female, p.female) }
    },
    { male: zeros(), female: zeros() },
  )

/** Headline target groups used as denominators by the department. */
export interface TargetGroups {
  total: number
  male: number
  female: number
  under5: number
  children0to14: number
  women15to49: number
  adults60plus: number
}

// Band indices: 0 = 0-4, 2 = 10-14, 3 = 15-19, 9 = 45-49, 12 = 60-64, 16 = 80+
export const targetGroups = (p: Profile): TargetGroups => ({
  total: sum(p.male) + sum(p.female),
  male: sum(p.male),
  female: sum(p.female),
  under5: p.male[0] + p.female[0],
  children0to14: range(p.male, 0, 2) + range(p.female, 0, 2),
  women15to49: range(p.female, 3, 9),
  adults60plus: range(p.male, 12, 16) + range(p.female, 12, 16),
})

export const institutionsIn = (wilayat: string | 'all'): RawInstitution[] =>
  wilayat === 'all' ? INSTITUTIONS : INSTITUTIONS.filter((i) => i.wilayat === wilayat)

/** Omani and expatriate totals per wilayat (or per institution within one). */
export const byWilayat = WILAYATS.map((w) => {
  const list = institutionsIn(w.en)
  const om = targetGroups(aggregate(list, 'omani'))
  const ex = targetGroups(aggregate(list, 'expat'))
  return { wilayat: w.en, wilayatAr: w.ar, omani: om.total, expat: ex.total, om }
})

/** Governorate Omani groups — the denominators used for coverage rates. */
export const govOmani = targetGroups(aggregate(INSTITUTIONS, 'omani'))

/** Catchments present in the wilayah sheets but absent from the summary sheet. */
export const notInSummary = INSTITUTIONS.filter((i) => !i.inSummary)
